name: 'test'

on:
    workflow_dispatch:
        inputs:
            a:
                required: false
                default: 'a'
            b:
                required: false
                default: 'b'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: ['${{ github.event.inputs.a }}', '${{ github.event.inputs.b }}']

    outputs:
      a: ${{ steps.test.outputs[0].test }}
      b: ${{ steps.test.outputs[1].test }}


    steps:
      - name: test
        id: test
        run: |
          echo "test=${{ env.test }}" >> "$GITHUB_OUTPUT"
        shell: bash
        env:
          test: ${{ matrix.test }}


      
  result:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: result
        run: |
          echo ${{ needs.test.outputs.a }}
          echo ${{ needs.test.outputs.b }}
        shell: bash